### ISSUE TITLE
Uruchamianie skryptów i prośba o sudo

### ISSUE THREAD

**Issue by Encryptize** [unkn0w/noobs#11]
Czy skrypty nie powinny sprawdzać, czy skrypt jest wywoływany z poziomu konta root? Moim zdaniem, z góry wrzucanie np. poleceń `apt install` bez `sudo` lub sprawdzania uprawnień może być nieco problematyczne dla nowych użytkowników. Oczywiście z góry zakładam, że korzystają ze zwykłych kont.

**Comment by szczot3k** [comment]
A może zamiast z góry zakładać, to wrzucić sprawdzanie EUID na początku?

```
if (( $EUID != 0 )); then
    echo "Please run as root"
    exit
fi
```
