### ISSUE TITLE
chce_smb.sh

### ISSUE THREAD

**Issue by krzyssiek** [unkn0w/noobs#123]
czy smb jest ustawione tak aby po zainstalowaniu od razu współpracowało z openvpn? Jeżeli nie jak to zrobić aby przez openvpn mógł zapiąć po smb do storage

**Comment by asc3rr** [comment]
No serwer smb jest po prostu wystawiony. Działa tak jak każda inna usługa.

**Comment by loper** [comment]
W razie problemów popraw wpis o nasłuchiwaniu w smb.conf:
```
[global]
interfaces = 127.0.0.0/8 eth0
```

**Comment by krzyssiek** [comment]
Pomoglby ktoś z instalacją i konfiguracja aby działa z openvpn

**Comment by krzyssiek** [comment]
@asc3rr

**Comment by loper** [comment]
A możesz opisać, co masz do tej pory zainstalowane i skonfigurowane? Openvpn działa w trybie klienta lub serwera, masz spięty tunel i jakąś adresację (np. 10.0.0.0/24) na obu końcach (mikrusie i jakieś stacji z windowsem)? Jesteś w stanie z tego hosta połączyć się po SSH na ten IP VPSa (port 22, nie srvXX:10XXX)?

**Comment by krzyssiek** [comment]
Mam postawimy na mikrusie openvpn z skryptu noobs. Próbuję zrobić aby client widział clients np aby po VPN było widać stronę która stoi na innym urządzeniu zapiętym po VPN i chciałbym aby po VPN był jeszcze po smb widoczny storage którego mam

**Comment by loper** [comment]
Właśnie do tego służy VPN. Wszystko co opisałeś jest możliwe i powinno działać out-of-the-box. Jedyny problem jaki widzę, to trasy. Sprawdź SSH i ping na adres serwera VPN.
W razie problemów możesz zacząć małymi kroczkami - ZeroTier oferuje taki gotowy VPN, żeby wykluczyć potencjalne błędy.

**Comment by krzyssiek** [comment]
Server VPN działa dobrze jedyne co nie działa to client to client

**Comment by loper** [comment]
Trasy (na VPS) dodaje się w ten sposób: `sudo ip r add 192.168.XX/24 dev tun0` (Twoja sieć domowa). Client-to-client powinien działać. Rozumiem, że masz 1x server VPN + 2x klient i chcesz udostępniać między tymi klientami? Jak już VPN jest połączony, to spróbuj zrestartować usługę "smbd".

**Comment by krzyssiek** [comment]
Dzisiaj się tym zajmę bo muszę przenieść server VPN na innego mikrusa

**Comment by asc3rr** [comment]
Z moich doświadczeń z vpn-ami wynika że masz dostęp do wewn. sieci(przynajmniej tak to działało na hackthebox). O ile to tak działa to możesz połączyć się po adresie 10.0.0.X:<port_smb>. Jeżeli chodzi o odcinanie dostępu ze świata to ja bym zablokował odpowiednie porty na ufw. 

Nie za bardzo wiem co chcesz osiągnąć.

**Comment by krzyssiek** [comment]
Chce osiągnąć aby móc z każdego miejsca na świecie zapiąć się po smb do storage ale też aby te pliki co tak będą aby były bezpieczene

**Comment by asc3rr** [comment]
Ja za bardzo Ci nie pomogę, nie wiem jak działają VPN'y. Wydaje mi się, że jak połączysz się z VPN'em to serwer smb będzie słuchał na localhoscie/adresie hosta.

**Comment by krzyssiek** [comment]
SMB działa bez zarzutu po VPN właśnie testowałem
