### ISSUE TITLE
Openvpn

### ISSUE THREAD

**Issue by krzyssiek** [unkn0w/noobs#125]
Chcę zainstalować openvpn na mirkus 1.0 i dostępne taki komunikat co zrobić?

Server hostname not known for key x

**Comment by archont94** [comment]
> Chcę zainstalować openvpn na mirkus 1.0 i dostępne taki komunikat co zrobić?
> 
> Server hostname not known for key x�

Podaj numer VPSa (np e123) i nazwę serwera (np srv06.mikr.us). Nie miałem możliwości sprawdzenia wszystkich możliwości.

**Comment by krzyssiek** [comment]
Na maluchu nie działa za to na srv10 działa bez problemu @archont94

**Comment by archont94** [comment]
@krzyssiek więc bądź tak miły i podaj potrzebne mi informacje to naprawię skrypt, bo wiem w którym miejscu jest problem. Po prostu muszę dodać mapowanie, a do tego potrzebuję numer VPSa (np e123) oraz nazwę serwera (np srv06.mikr.us).

**Comment by krzyssiek** [comment]
X112 maluch.mikr.us @archont94

**Comment by archont94** [comment]
@loper #126

**Comment by archont94** [comment]
@krzyssiek tak, tylko zaktualizuj skrypt.

**Comment by krzyssiek** [comment]
Wszytko działa już git dzięki wielkie za pomoc @archont94

**Comment by krzyssiek** [comment]
@archont94 a wiesz może jak zrobić aby za pośrednictwem openvpn wystawić na porcie mikrusowym port z urządzenia zapiętego po VPN?

**Comment by archont94** [comment]
@krzyssiek Na mikrusie musisz przekierować dany port do urządzenia w sieci VPN (używając wewnętrznej adresacji).

**Comment by krzyssiek** [comment]
A pomógł/aś byś z tym bo próbowalem ale mi nadal nie dziala. Możemy na mesie? Link do mnie do kontaktu przez mesa https://m.me/krzyssiek2007
