### ISSUE TITLE
Webmin

### ISSUE THREAD

**Issue by krzyssiek** [unkn0w/noobs#132]
Zainstalowałem webmina i on nie instaluje z sobą żadnego servera www i nie ma go na żadnym porcie. Jednosłownie mi nie działa

**Comment by stefopl** [comment]
Webmin powinien chyba działać też bez dodatkowego serwera WWW. Dla pewności użyj chce_LAMP.sh przed chce_webmina.sh.
W wolnej chwili przyjrzę się temu skryptowi.
(Sprawdziłem na prawie czystym serwerze z LAMP i SOA#1 dziwne u mnie działa)
Webmin powinien być dostępny pod adresem typu https://srv0X.mikr.us:30XXX jako dane do logowanie dane roota lub dowolnego usera z sudo. 
Oczywiście X zastąpić zgodnie z danymi serwera w panelu
