### ISSUE TITLE
GitActions - testowanie wykonywalności plików

### ISSUE THREAD

**Issue by loper** [unkn0w/noobs#135]
Czy w takim GitActions da się dodać krok sprawdzający, czy nowy skrypt ma mode 0755? To by pilnowało, żeby wszystko było wykonywalne. @mikasjp

**Comment by mikasjp** [comment]
Czy dobrze rozumiem, że chcesz, żeby Git pamiętał uprawienia plików ze skryptami?
Poczytałem trochę na ten temat i wydaje mi się, że to nie jest dobry pomysł.
* Git nie ma takiej możliwości "out of the box". Wymaga to dodatkowej konfiguracji.
* Co jeśli ktoś pisze skrypt i używa Gita pod innym OS, który ma odmienny system uprawnień (np. Windows)?
* Czy nie lepiej zmodyfikować skrypt `https://noobs.mikr.us` w taki sposób, żeby po sklonowaniu repo nadawał odpowiednie uprawnienia?

**Comment by loper** [comment]
Chciałbym, aby jako 1 z kroków testowania było wykonywane sprawdzanie, czy plik posiada tryb wykonywalny.

**Comment by loper** [comment]
Scenariusz:
* User dodaje nowy skrypt.
* Zapomina jednak o tym, co większość - o nadaniu flagi wykonywalności (+x).
* Test w Actions wyłapuje taki błąd i od razu sypie błędem.

**Comment by mati97xdd** [comment]
https://github.com/mati97xdd/noobs/commit/2f155df1298c7dc389fc921cb7e807cbd2d1a9f8
Tak będzie ok?

**Comment by loper** [comment]
Z samego czytania kodu - dokładnie o coś takiego mi chodziło. Da się to podpiąć do obecnych testów? Dzięki, L.
