### ISSUE TITLE
Transient problem: HTTP error przy odpaleniu ./chce_openvpn.sh

### ISSUE THREAD

**Issue by Seba0855** [unkn0w/noobs#148]
Przy odpalaniu skryptu ./chce_openvpn.sh wyskakuje error:
```
Warning: Transient problem: HTTP error Will retry in 1 seconds. 5 retries
Warning: left.
100  7411    0  7411    0     0   226k      0 --:--:-- --:--:-- --:--:--  226k
Warning: Transient problem: HTTP error Will retry in 2 seconds. 4 retries
Warning: left.
100  7434    0  7434    0     0   250k      0 --:--:-- --:--:-- --:--:--  250k
Warning: Transient problem: HTTP error Will retry in 4 seconds. 3 retries
Warning: left.
```

który nie pozwala na dalszą instalację skryptu. Skrypt instalacyjny bez problemu zaciąga się ze stronki podanej w `chce_openvpn`, ale któraś z poniższych flag sprawia problem i openvpn się nie chce zainstalować.
```
export AUTO_INSTALL=y
export APPROVE_INSTALL=y
export APPROVE_IP=y
export ENDPOINT="$host"
export IPV6_SUPPORT=n
export PORT_CHOICE=2
export PORT=$port
export PROTOCOL_CHOICE=1
export DNS=1
export COMPRESSION_ENABLED=n
export CUSTOMIZE_ENC=n
export PASS=1
```

**Comment by stefopl** [comment]
Sprawdziłem na mikrusie 3.0 z serii ```srv09```, czyli ```g``` z Ubuntu.
Warningi były, ale sam VPN uruchamia się poprawnie. 
Upewnij się, że na porcie ```20XXX``` nie stoi żadna usługa (```XXX``` to numer serwera).
Tu konfiguracja VPN jest na UDP więc do dyspozycji masz jeszcze port ```30XXX```.
Możesz uruchomić skrypt instalacji z parametrem ```--port 30XXX```

Jeżeli problem dalej występuje, napisz jak wersja serwera i jaki system?

**Comment by Seba0855** [comment]
Okej, jak się okazuje, po ponownej próbie po prawie 2 tygodniach jednak zadziałało. Może chwilowy problem z serwerem lub coś. W takim razie dzięki za pomoc! :)
