### ISSUE TITLE
wez ty człowieku podawaj gdzies jakieś normlane dane kontaktowe?

### ISSUE THREAD

**Issue by gotshadowbantempaccount** [unkn0w/noobs#150]
Blokujesz adresy IP cloudflare z singapury i twoje serwisy sa tam nie dostępne bo cloudlfare nie podaje wszystkich adresów IP do whitelistowania a oni maja to gdzies btw. i pewnie ty że połowę azji blokujesz przez to

co ja mam kombinowac polski numer telefonu by utworzy kontao na wykopie by wysłac tobie jakąs wiadomosc moze morsem

**Comment by y0rune** [comment]
Cześć!

Najważniejsze informacje znajdziesz na stronie: https://www.notion.so/mrugalski/MIKR-US-Don-t-Panic-5c3bdde2e0b545e7866524fc117446c3
Także możesz wystawić ticket za pośrednictwem panelu (https://mikr.us/panel/). Wtedy admini będą wstanie Ci pomóc ;) 

Pozdrawiam

**Comment by stefopl** [comment]
[mikr.us stopka](https://mikr.us/)
```
Kontakt: pomoc@mikr.us
```
Korzystając z usług akceptujesz [regulamin i politykę prywatności](https://mikr.us/regulamin_i_polityka.html)
```
10. Dane kontaktowe
  1. Preferowaną formą komunikacji ze sprzedającym jest adres mailowy: mikrus@mrugalski.pl
 
```

**Comment by gotshadowbantempaccount** [comment]
ludzie czytajcie z zrozumieniem, rozumiem że nie jesteście osobami technicznymi ale jakąś wiedzie w temacie nawet minimalną musicie posiadać. JA sobie czasami czytam głupiego unknownes i tyle i teraz bo clpoudflare sądze ze server nie jest online

![image](https://user-images.githubusercontent.com/88304290/210121667-b624c874-2745-481f-84d9-1a5e553ea1ac.png)

po 4 razie wchodzi czasami

![image](https://user-images.githubusercontent.com/88304290/210121694-66a083dc-7cba-43de-8e64-f5b5db003f84.png)

**Comment by unkn0w** [comment]
> wez ty człowieku podawaj gdzies jakieś normlane dane kontaktowe

Pierwszy wynik z google pod moim nickiem, nazwiskiem, nazwą newslettera lub nazwą firmy powinien to zwrócić.

> czy blokujecie np. 172.68.6.144, 172.68.6.145 Thailand 

Słuszna uwaga. Oba były blokowane, ale już nie są.
Dodałem odpowiednie podsieci CF do białej listy. Problem powinien być rozwiązany.

**Comment by gotshadowbantempaccount** [comment]
ciul z tym wejdź do Rules w cloudflare --> Transform Rules -->  HTTP Request Header Modification
Dodaj nagłównek np "Niematakiegonaglowkatoblokuj" wartosc "tajne8888888"

I sprawdzaj jeżeli nie ma headera: Niematakiegonaglowkatoblokuj o wartośćiu tajne8888888 to blokuj połaczenie i nie baw sie z blokowaniem po adresach IP bo nie aktualniaja ich


HTTP Request Header Modification

**Comment by gotshadowbantempaccount** [comment]
****** @unkn0w - rozwiązanie w poście powyżej

![image](https://user-images.githubusercontent.com/88304290/211360878-99da6388-af47-48c9-bf21-65e3ca801fff.png)
