### ISSUE TITLE
chce_2fa_otp.sh - zabezpieczenie skryptu

### ISSUE THREAD

**Issue by unkn0w** [unkn0w/noobs#158]
Do poprawy:

1. Skrypt prosi o uruchomienie dodatkowej sesji SSH, ale nie czeka na jej uruchomienie. Powinno być jakieś oczekiwanie na ENTER
2. skrypt uruchamia 'google-authenticator', ale nie sprawdza, czy udało się poprawnie przejść konfiguracje. Od razu zabezpiecza SSH, co może doprowadzić do zablokowania serwera
3. Skrypt nie sprawdza, czy Authenticator już istnieje w /etc/pam.d/sshd - możliwe jest wielokrotne dodanie tego samego pluginu i zablokowanie serwera

**Comment by loper** [comment]
@Encryptize

**Comment by loper** [comment]
+6
