### ISSUE TITLE
chce_LAMP.sh - dynamiczna wersja PHP

### ISSUE THREAD

**Issue by unkn0w** [unkn0w/noobs#160]
Skrypt instaluje PHP 8.0.
Powinien sprawdzać, jaka jest najnowsza dostępna w repozytorium wersją i to ją zainstalować.

**Comment by loper** [comment]
@rupinski75 na którym VPS dodać bonus?

**Comment by krzysztof-rupinski** [comment]
@loper Dzięki, nie  mam vpsa. Można dodać komuś kto potrzebuje :)

**Comment by rupinski75** [comment]
@loper Dzięki, nie mam vpsa. Można dodać komuś kto potrzebuje :)

**Comment by loper** [comment]
Możesz dostać VPS na 2 miesiące, jeśli chcesz :)
