### ISSUE TITLE
chce_wireguard.sh - korzysta z Wireguarda z 2019 roku

### ISSUE THREAD

**Issue by unkn0w** [unkn0w/noobs#163]
Może warto przesiąść się na nowszą wersję paczki?
Warto przetestować, czy np. wersje z 2022 lub 2023 bez problemu ruszą na Mikrusie.

**Comment by sabbath88** [comment]
PR czeka na review ;)

**Comment by loper** [comment]
jaki masz ID VPSa?

**Comment by loper** [comment]
wciąż aktywne, prośba o naprawienie i PRZETESTOWANIE na mikrusie

**Comment by sabbath88** [comment]
Poprawka utworzona. Testy w trakcie.

W dniu niedz., 17.09.2023 o 22:52 loper ***@***.***>
napisał(a):

**Comment by sabbath88** [comment]
+PR

**Comment by ferexio** [comment]
@loper do zamknięcia?

**Comment by ferexio** [comment]
@loper z tego co widzę to ten issue powinien iść do zamknięcia
