### ISSUE TITLE
chce_postgres_backup.sh - zabezpieczenie skryptu

### ISSUE THREAD

**Issue by unkn0w** [unkn0w/noobs#164]
Skrypt zawsze usuwa stare backupy, nawet jeśli aktualny backup się nie wykonał.
Może to doprowadzić do sytuacji, że stare backupy będą znikać, a nowe się nie pojawiać.
Procedura sprzątania powinna być wywołana jedynie po udanym przygotowaniu backupu.

Ustawiłbym także mniejszy limit archiwum backupów. 180 dni przy dostatecznie dużych bazach na 100% zapcha dysk serwera.

**Comment by MariuszDrabik** [comment]
Zajmę sie tym.

**Comment by MariuszDrabik** [comment]
A właśnie do tego siadłem ;-(

**Comment by loper** [comment]
@MariuszDrabik przecież nie jest zamknięty issue - można działać dalej 👍

**Comment by MariuszDrabik** [comment]
Nawet mam działającą wersję. Ale nie mogę wypchnąć gałęzi. Jak ti na githubie robi się pull requesty?
