### ISSUE TITLE
chce_jenkins.sh - stały numer portu

### ISSUE THREAD

**Issue by unkn0w** [unkn0w/noobs#167]
Port powinien być zdefiniowany w zmiennej na początku skryptu, a nie wpisany na stałe jako 80.

**Comment by BElluu** [comment]
Ogarnę. Czy ta zmienna ma być po prostu do ustawienia poprzez edycję skryptu, czy oczekujemy od użytkownika portu przy uruchomieniu jako input?

**Comment by loper** [comment]
Możesz zrobić tak: JENKINS_PORT=30878 ./chce_jenkins.sh

**Comment by loper** [comment]
PR musi być tutaj, w repo unkn0w

**Comment by pablowyourmind** [comment]
Czy #206 rozwiązuje według Was ten problem w pełni czy warto coś tam jeszcze poprawić?

**Comment by loper** [comment]
Dzięki, rozwiązuje, więc zamykam.
