### ISSUE TITLE
chce_ssh_config.sh - uzupełnienie danych

### ISSUE THREAD

**Issue by ferexio** [unkn0w/noobs#190]
Dlaczego?
Wraz ze wzrostem ilości maszyn Mikrusa potrzebne jest także uzupełnienie informacji o tym w pliku chce_ssh_config, gdyż jeżeli ktoś będzie posiadał maszynę spoza zakresu to może pójść coś nie tak.

Co?
- uzupełnić ilość maszyn w pliku
- przemyśleć sposób przechowywania nazw maszyn w skrypcie i zaproponować możliwe rozwiązania
- po zatwierdzeniu rozwiązania wdrożyć zmiany do skryptu

**Comment by stefopl** [comment]
Skoro aktualna lista serwerów znajduje się tutaj https://mikr.us/serwery.txt najlepiej byłoby sprawdzać ten adres. Z drugiej strony niektóre skrypty można wykonać offline więc lista powinna być też w repozytorium noobs.

Przy okazji mam taką uwagę: Przesyłany na serwer klucz publiczny w pliku posiada user@host:port tego serwera. 
W efekcie gdy łącze się do serwera z wielu urządzeń w authorized_keys mam kilka wpisów root@mini01.mikr.us:10500
Chyba lepiej, aby w tym miejscu był wpisany user@hostname urządzanie, na którym wykonujemy skrypt np. user@WINDOWS-WSL
