### ISSUE TITLE
[NEW] Dodać instalator Nextclouda

### ISSUE THREAD

**Issue by unkn0w** [unkn0w/noobs#2]
Instalator powinien postawić całe środowisko wraz z bazą danych MariaDB (domyślnie jest SQLite).

**Ważne**: jeśli instalator wykryje obecność katalogu /storage/ to tam domyślnie powinien trzymać pliki użytkownika.

**Comment by unkn0w** [comment]
> Oficjalnie Nextcloud wspiera tylko Apache, Natomiast da się trochę go zoptymalizować tak, aby działał na - jednak lżejszym - NGINX, Która opcja była by tu preferowana?

Myślę, że Apache będzie w zupełności wystarczający. Unikniemy w ten sposób problemów z obsługą plików ".htaccess" i koniecznością przepisywania wszystkich ścieżek na rewrite Nginx.

**Comment by BartoszSiemienczuk** [comment]
@maniek205 @unkn0w może zamiast duplikować instalację LAMP-a można po prostu przed instalacją nextcloud-a wywołać chce_LAMP.sh? chyba, że każdy ze skryptów ma być w 100% samodzielny, ale wtedy będziemy mieli duplikację i rozjazdy, szczególnie przy aplikacjach webowych jak Nextcloud.

**Comment by maniek205** [comment]
W sumie racja, mogę używać skryptu i uzupełnić tylko brakujące paczki. Problem może się pojawić później kiedy zmiany w jednym skrypcie spowodują defekt w drugim. @unkn0w w którym kierunku powinniśmy się tutaj kierowac ?

**Comment by unkn0w** [comment]
@maniek205 - wywołaj na start **chce_LAMP.sh**. Będzie prościej.
Do tego hardcodowane hasła w środku skryptu to nie jest najlepszy pomysł, bo zgaduję, że 99% userów tego nigdy nie zmieni i będziemy mieć dziesiątki userów z hasłami 'admin'.

**Comment by kry008** [comment]
Sam instalowałem NextCloud na storage na apache2 śmiga, że aż miło.
