### ISSUE TITLE
scripts/chce_wireguard.sh Failed to stop resolvconf.service

### ISSUE THREAD

**Issue by januszmiller** [unkn0w/noobs#204]
Wykonanie skryptu chce_wireguard.sh na Ubuntu 23.04 kończy się błędem:
"Failed to stop resolvconf.service: Unit resolvconf.service not loaded."

1. TUN/TAP/FUSE włączone
2. Powłoka zsh

**Comment by loper** [comment]
Poprawka wrzucona do mastera.
