### ISSUE TITLE
chce_jenkins.sh - aktualizacja + usprawnienia

### ISSUE THREAD

**Issue by pablowyourmind** [unkn0w/noobs#206]
Skrypt chce_jenkins.sh wymaga kilku aktualizacji:
- zmienił się klucz dla repozytorium Jenkinsa. Więcej informacji można znaleźć tutaj:
https://www.jenkins.io/blog/2023/03/27/repository-signing-keys-changing/
- Skończyło się wsparcie dla Javy 11, należy przejść na Javę 17
![java11-end](https://github.com/user-attachments/assets/4daae000-93c9-4cbf-a389-c2c80f800682)
więcej informacji można znaleźć tutaj: 
https://www.jenkins.io/doc/book/platform-information/upgrade-java-to-17/

Dodatkowo warto dodać kilka usprawnień:
- Ograniczenie przydziału RAMu dla Jenkinsa, aby świeża instancja Jenkinsa nie spowalniała znacząco serwera
- Pytanie użytkownika, na jakim porcie Jenkins ma nasłuchiwać

**Comment by loper** [comment]
merged PR https://github.com/unkn0w/noobs/pull/207
