### ISSUE TITLE
VNC 

### ISSUE THREAD

**Issue by krzyssiek** [unkn0w/noobs#27]
Automatyczne instalacja VNC które będzie dziać po port forwarding

**Comment by loper** [comment]
A stawial ktoś X-y na mikrusie, że potrzebuje dostępu po VNC?

**Comment by unkn0w** [comment]
Nie wydaje mi się, aby ktoś potrzebował VNC.
W historii Mikrusa było dwóch takich userów, więc moim zdaniem szkoda czasu na pisanie skryptu pod to. Zamykam temat.
