### ISSUE TITLE
[NEW] Dodać instalator OpenVPN

### ISSUE THREAD

**Issue by unkn0w** [unkn0w/noobs#3]
Instalator powinien sam pobierać takie dane jak dostępny numer portu (na podstawie ID maszyny: 20000 + ID), czy publiczny adres serwera, na którym jest uruchamiany.

Cała instalacja powinna być bezobsługowa.

**Comment by archont94** [comment]
Zajmę się tym.

**Comment by archont94** [comment]
#69
