### ISSUE TITLE
[NEW] Dodać instalator Wordpressa

### ISSUE THREAD

**Issue by unkn0w** [unkn0w/noobs#5]
Skrypt powinien najpierw wywołać chce_LAMP.sh, a następnie ściągnąć najnowszą wersję wordpressa (polska wersja jezykowa) ze strony producenta, rozpakować ją i wrzucić do odpowiedniego katalogu.

**Comment by rafalmasiarek** [comment]
możesz przydzielić to zadanie do mnie :)

**Comment by rafalmasiarek** [comment]
poszedl pull https://github.com/unkn0w/noobs/pull/22

**Comment by unkn0w** [comment]
Gotowe - skrypt dodany do repo
