### ISSUE TITLE
[NEW][SECURITY] server hardening

### ISSUE THREAD

**Issue by loper** [unkn0w/noobs#57]
Celem jest odpowiednie dokonfigurowanie usług, aby system był mniej podatny na ataki. Propozycja zmian:
* konfiguracja SSHD (allowed users, permit root login, password auth, itp.)
* instalacja Lynisa do skanowania i raportowania
* instalacja logwatch (+ cron i pusher) dla raportu z aktywności na serwerze
* instalacja narzędzi do sprawdzania bezpieczeństwa zainstalowanych pakietów na Debianie/Ubuntu: ('debsums', 'unattended-upgrades', 'apt-show-versions')

**Comment by asc3rr** [comment]
Jak często logwatch ma być uruchamiany?

**Comment by unkn0w** [comment]
Zaakceptowałem pierwszą wersję skryptu 👍
