### ISSUE TITLE
[NEW] chce_backup

### ISSUE THREAD

**Issue by loper** [unkn0w/noobs#64]
Skrypt automatyzujący backupowanie najważniejszych katalogów. Mikrus oferuje 200MB na zabezpieczenie np. konfiguracji - skrypt powinień uwzględniać go jako miejsce na archiwum (np. /etc/). Jeśli ktoś ma wykupiony storage, to backupy najlepiej tam trzymać (np. /storage/backup). Domyślnie ważna jest kopia zapasowa "/etc" oraz "/home".

**Comment by asc3rr** [comment]
Gdzie mają znajdować się backupy gdy user nie ma storage'a?

**Comment by asc3rr** [comment]
> 
> 
> Gdzie mają znajdować się backupy gdy user nie ma storage'a?
Dobra, poinformuję userów aby uruchomili backup z panelu(strych)
