### ISSUE TITLE
[NEW] Dodać instalator środowiska do .NET

### ISSUE THREAD

**Issue by unkn0w** [unkn0w/noobs#9]
Stack ma uruchamiać aplikacje ASP.net na Apache z użyciem MONO.

**Comment by mikasjp** [comment]
A może .NET Core, .NET 5, .NET 6?

**Comment by unkn0w** [comment]
Podstawowy skrypt został stworzony - zamykam issue.
Może warto go rozbudować o dodatkowe opcje? 🤔
